cmake_minimum_required(VERSION 3.8)
project(robot_description)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch urdf worlds config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(test_robot_description test/test_robot_description.py)
endif()
ament_package()
